package edu.usc.pgroup.cloud.iaassim.core;

public enum SimulationEventTag {
	Undefined, 
	VM_CREATE_REQUEST_WITH_ACK, 
	VM_CREATE_RESPONSE_ACK, 
	CLOUD_CHARACTERISTICS_REQ,
	CLOUD_CHARACTERISTICS_RES, 
	CLOUDLET_SUBMIT, 
	PE_SUBMIT_ACK, 
	PE_RETURN, 
	VM_CLOUD_EVENT, 
	INCOMING_DATA, 
	DATA_SOURCE_EVENT, COORDINATOR_ACTION_EVENT, SCALE_IN, SCALE_OUT, RUNTIME_PE_CHANGE_REQ, RUNTIME_VM_CHANGE_REQ, COORDINATOR_MONITOR_EVENT, CLOUDLET_REMOVE, PE_REMOVE_ACK, VM_SHUTDOWN_REQUEST_WITH_ACK, VM_SHUTDOWN_RESPONSE_ACK 
}
